language: python
sudo: false
python:
    - '3.4'
    - '3.3'
    - '3.2'
    - '2.7'
    - '2.6'
    - pypy
    - pypy3
install:
    - pip install biopython || true
    - python setup.py install
    - pip install coveralls
before_script:
    - /usr/bin/pip install biopython
    - if [ ! -e "tests/data/genes.fasta" ]; then /usr/bin/python tests/data/download_gene_fasta.py; fi
script: nosetests --with-coverage --cover-package=pyfaidx
deploy:
  provider: pypi
  user: mdshw5
  password:
    secure: WaAW6Vk1yjC851PKaeiJGNyZ6wZ2baqlixUSvRDXoT673yFrlp32IMHofmP/TwVxnLMfQxhAb3r7dYYDYnNw4n3vPInJ+Yy35RG1WQ2XUOpOEZ8n2fWczxKfkJjQ5ob03DCSFPeL5h+FYfyHRAfPb9K8OtEawKRvCfaUXE0teko=
  on:
    all_branches: true
    python: 2.6
    tags: true
    repo: mdshw5/pyfaidx
cache:
    - wheelhouse
    - tests/data
    - pip
after_success:
    - coveralls
