language: python
sudo: false
python:
    - '3.4'
    - '3.3'
    - '3.2'
    - '2.7'
    - '2.6'
    - pypy
    - pypy3
install:
    - pip install biopython || true
    - python setup.py install
    - pip install coveralls
    - pip wheel -f wheelhouse cython || true
    - pip install -f wheelhouse cython || true
    - pip wheel -f wheelhouse pysam || true
    - pip install -f wheelhouse pysam || true
    - pip install https://github.com/brentp/fastahack-python/archive/master.zip
    - pip install pyfasta || true
    - if [ ! -f samtools-1.2 ]; then wget -q -O - https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2 | tar -xjv; fi
    - cd samtools-1.2
    - make
    - export PATH=$PATH:$PWD
    - cd ..
    - pip install pyvcf
before_script:
    - /usr/local/bin/pip install --user biopython
    - /usr/bin/python tests/data/download_gene_fasta.py
script: nosetests --with-coverage --cover-package=pyfaidx
deploy:
  provider: pypi
  user: mdshw5
  password:
    secure: WaAW6Vk1yjC851PKaeiJGNyZ6wZ2baqlixUSvRDXoT673yFrlp32IMHofmP/TwVxnLMfQxhAb3r7dYYDYnNw4n3vPInJ+Yy35RG1WQ2XUOpOEZ8n2fWczxKfkJjQ5ob03DCSFPeL5h+FYfyHRAfPb9K8OtEawKRvCfaUXE0teko=
  on:
    all_branches: true
    python: 2.6
    tags: true
    repo: mdshw5/pyfaidx
cache:
    directories:
        - tests/data
        - samtools-1.2
        - wheelhouse
after_success:
    - coveralls
    - if [ $TRAVIS_PYTHON_VERSION == '3.4' ] && [ -n $TRAVIS_TAG ]; then python scripts/benchmark.py 1000; fi
