language: python
sudo: false
python:
- '3.4'
- '3.3'
- '3.2'
- '2.7'
- '2.6'
- pypy
- pypy3
install:
- pip wheel cython
- pip install -f wheelhouse cython
- pip wheel pysam
- pip install -f wheelhouse pysam https://github.com/brentp/fastahack-python/archive/master.zip
- pip install pyfasta
- pip install biopython || true
- pip install -e .
- pip install coveralls
script: nosetests --with-coverage --cover-package=pyfaidx
deploy:
  provider: pypi
  user: mdshw5
  password:
    secure: WaAW6Vk1yjC851PKaeiJGNyZ6wZ2baqlixUSvRDXoT673yFrlp32IMHofmP/TwVxnLMfQxhAb3r7dYYDYnNw4n3vPInJ+Yy35RG1WQ2XUOpOEZ8n2fWczxKfkJjQ5ob03DCSFPeL5h+FYfyHRAfPb9K8OtEawKRvCfaUXE0teko=
  on:
    all_branches: true
    python: 2.6
    tags: true
    repo: mdshw5/pyfaidx
cache:
    - wheelhouse
after_success:
    - coveralls
