language: python
python:
- '3.3'
- '3.2'
- '2.7'
- '2.6'
- pypy
install:
- pip install -r requirements.txt
- python setup.py install
script: nosetests
deploy:
  provider: pypi
  user: mdshw5
  password:
    secure: iAxRYdOqctdYzUtDW63QQAjKm6UnGUIA3zP2uYEAEaobMCJwba2JW6pp/XojgzcMTHrvo0y7jdn8njGW1Paj62YtoRXUto9za9Uo92d3J5yORQa4irjtofDF1HuF/BFr+eJNBAtrNTIVnH9BH1+GYJoElWLxqW8GAA1XKzSYgVs=
  on:
    branch: master
    tags: true
    repo: mdshw5/pyfaidx
